# ===========================
#  Switch Zigbee de sala
#  Maneja todos los botones en una sola automatizacion
#  Unificado (tap / double / hold)
# ===========================
- alias: Switch sala
  id: switch_sala_1
  mode: single
  trigger:
    # --- TAP (single) ---
    - id: b1_single
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 1_single
      discovery_id: 0xb4e3f9fffe14e641 action_1_single

    - id: b2_single
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 2_single
      discovery_id: 0xb4e3f9fffe14e641 action_2_single

    - id: b3_single
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 3_single
      discovery_id: 0xb4e3f9fffe14e641 action_3_single

    - id: b4_single
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 4_single
      discovery_id: 0xb4e3f9fffe14e641 action_4_single

    # --- DOUBLE TAP ---
    - id: b1_double
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 1_double
      discovery_id: 0xb4e3f9fffe14e641 action_1_double

    - id: b2_double
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 2_double
      discovery_id: 0xb4e3f9fffe14e641 action_2_double

    - id: b3_double
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 3_double
      discovery_id: 0xb4e3f9fffe14e641 action_3_double

    - id: b4_double
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 4_double
      discovery_id: 0xb4e3f9fffe14e641 action_4_double

    # --- HOLD ---
    - id: b1_hold
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 1_hold
      discovery_id: 0xb4e3f9fffe14e641 action_1_hold

    - id: b2_hold
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 2_hold
      discovery_id: 0xb4e3f9fffe14e641 action_2_hold

    - id: b3_hold
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 3_hold
      discovery_id: 0xb4e3f9fffe14e641 action_3_hold

    - id: b4_hold
      platform: device
      domain: mqtt
      device_id: 6a1775371239157ec4543f3c5d7fb5b5
      type: action
      subtype: 4_hold
      discovery_id: 0xb4e3f9fffe14e641 action_4_hold

  condition: []

  action:
    - choose:
        # ========= SINGLE =========
        - conditions: { condition: trigger, id: b1_single }
          sequence:
            - service: script.switch_sala_b1_single

        - conditions: { condition: trigger, id: b2_single }
          sequence:
            - service: script.switch_sala_b2_single

        - conditions: { condition: trigger, id: b3_single }
          sequence:
            - service: script.switch_sala_b3_single

        - conditions: { condition: trigger, id: b4_single }
          sequence:
            - service: script.switch_sala_b4_single

        # ========= DOUBLE =========
        - conditions: { condition: trigger, id: b1_double }
          sequence:
            - service: script.switch_sala_b1_double

        - conditions: { condition: trigger, id: b2_double }
          sequence:
            - service: script.switch_sala_b2_double

        - conditions: { condition: trigger, id: b3_double }
          sequence:
            - service: script.switch_sala_b3_double

        - conditions: { condition: trigger, id: b4_double }
          sequence:
            - service: script.switch_sala_b4_double

        # ========= HOLD =========
        - conditions: { condition: trigger, id: b1_hold }
          sequence:
            - service: script.switch_sala_b1_hold

        - conditions: { condition: trigger, id: b2_hold }
          sequence:
            - service: script.switch_sala_b2_hold

        - conditions: { condition: trigger, id: b3_hold }
          sequence:
            - service: script.switch_sala_b3_hold

        - conditions: { condition: trigger, id: b4_hold }
          sequence:
            - service: script.switch_sala_b4_hold
