# Paquete: Git Sync para Home Assistant
# Incluye comandos push/pull del repo de /config
# con notificaciones en HA y configuración de SSH forzada

shell_command:
  git_push_config: >
    sh -c "
      export HOME=/config &&
      GIT_SSH_COMMAND='ssh -i /config/.ssh/id_ed25519 -o StrictHostKeyChecking=no' &&
      cd /config &&
      CHANGES=$(git status --porcelain) &&
      if [ -n \"$CHANGES\" ]; then
        git add . &&
        git commit -m \"Commit desde Home Assistant - $(date '+%Y-%m-%d %H:%M:%S')\" -m \"Archivos: $CHANGES\" &&
        if git push origin main; then
          curl -s -X POST -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4YzY1MjEyYTU2N2Y0NDUzYjczYTVkOTJlYmRiMTQ4NiIsImlhdCI6MTc1NTE0ODQyOSwiZXhwIjoyMDcwNTA4NDI5fQ.F3uDb02YtUclcLvivzeoPGzxyye23-cWsZRssEsvooc' \
               -H 'Content-Type: application/json' \
               -d '{\"title\": \"Git Push\", \"message\": \"Push a GitHub completado con éxito\"}' \
               http://192.168.0.202:8123/api/services/persistent_notification/create
        else
          curl -s -X POST -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4YzY1MjEyYTU2N2Y0NDUzYjczYTVkOTJlYmRiMTQ4NiIsImlhdCI6MTc1NTE0ODQyOSwiZXhwIjoyMDcwNTA4NDI5fQ.F3uDb02YtUclcLvivzeoPGzxyye23-cWsZRssEsvooc' \
               -H 'Content-Type: application/json' \
               -d '{\"title\": \"Git Push\", \"message\": \"Error al hacer push a GitHub\"}' \
               http://192.168.0.202:8123/api/services/persistent_notification/create
        fi
      else
        curl -s -X POST -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4YzY1MjEyYTU2N2Y0NDUzYjczYTVkOTJlYmRiMTQ4NiIsImlhdCI6MTc1NTE0ODQyOSwiZXhwIjoyMDcwNTA4NDI5fQ.F3uDb02YtUclcLvivzeoPGzxyye23-cWsZRssEsvooc' \
             -H 'Content-Type: application/json' \
             -d '{\"title\": \"Git Push\", \"message\": \"No hay cambios para subir\"}' \
             http://192.168.0.202:8123/api/services/persistent_notification/create
      fi
    "

  git_pull_config: >
    sh -c "
      export HOME=/config &&
      GIT_SSH_COMMAND='ssh -i /config/.ssh/id_ed25519 -o StrictHostKeyChecking=no' &&
      cd /config &&
      if git pull origin main; then
        curl -s -X POST -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4YzY1MjEyYTU2N2Y0NDUzYjczYTVkOTJlYmRiMTQ4NiIsImlhdCI6MTc1NTE0ODQyOSwiZXhwIjoyMDcwNTA4NDI5fQ.F3uDb02YtUclcLvivzeoPGzxyye23-cWsZRssEsvooc' \
             -H 'Content-Type: application/json' \
             -d '{\"title\": \"Git Pull\", \"message\": \"Pull de GitHub completado con éxito\"}' \
             http://192.168.0.202:8123/api/services/persistent_notification/create
      else
        curl -s -X POST -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4YzY1MjEyYTU2N2Y0NDUzYjczYTVkOTJlYmRiMTQ4NiIsImlhdCI6MTc1NTE0ODQyOSwiZXhwIjoyMDcwNTA4NDI5fQ.F3uDb02YtUclcLvivzeoPGzxyye23-cWsZRssEsvooc' \
             -H 'Content-Type: application/json' \
             -d '{\"title\": \"Git Pull\", \"message\": \"Error al hacer pull de GitHub\"}' \
             http://192.168.0.202:8123/api/services/persistent_notification/create
      fi
    "

  git_pull_config_force: >
    sh -c "
      export HOME=/config &&
      GIT_SSH_COMMAND='ssh -i /config/.ssh/id_ed25519 -o StrictHostKeyChecking=no' &&
      cd /config &&
      git fetch origin main &&
      git reset --hard origin/main &&
      curl -s -X POST -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4YzY1MjEyYTU2N2Y0NDUzYjczYTVkOTJlYmRiMTQ4NiIsImlhdCI6MTc1NTE0ODQyOSwiZXhwIjoyMDcwNTA4NDI5fQ.F3uDb02YtUclcLvivzeoPGzxyye23-cWsZRssEsvooc' \
           -H 'Content-Type: application/json' \
           -d '{\"title\": \"Git Pull Forzado\", \"message\": \"Pull forzado completado, cambios locales descartados\"}' \
           http://192.168.0.202:8123/api/services/persistent_notification/create
    "

automation:
  - alias: Git Push diario
    trigger:
      - platform: time
        at: "03:00:00"
    action:
      - service: shell_command.git_push_config

  - alias: Git Push al reiniciar HA
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: shell_command.git_push_config

script:
  git_push:
    alias: Git Push a GitHub
    sequence:
      - service: shell_command.git_push_config
    mode: single

  git_pull:
    alias: Git Pull de GitHub
    sequence:
      - service: shell_command.git_pull_config
    mode: single

  git_pull_force:
    alias: Git Pull Forzado de GitHub
    sequence:
      - service: shell_command.git_pull_config_force
    mode: single
