# ===========================================================
#  SALA DE ESTAR — CONTROL POR MOVIMIENTO (v9 con helpers de estrategia)
#  - 2 automatizaciones: motion detected / motion clear
#  - Sin scripts ni transiciones. Sólo turn_on / turn_off / brightness_pct
#  - Estrategia por franja elegible desde UI:
#       * scene      → usa la escena definida para esa franja
#       * brightness → enciende al % definido para esa franja
#       * fallback   → intenta RESTAURAR SNAPSHOT; si no hay, usa % fallback de esa franja
#  - Temporizadores visibles: timer.apagado_sala (total) / timer.preaviso_sala (preaviso)
#  - Área usada: "sala_de_estar" (area_id). Ajustá si tu área difiere.
# ===========================================================

homeassistant:
  customize: {}

# ------------------------
# HELPERS
# ------------------------
input_boolean:
  # Bypass total: si está ON, la lógica no actúa (no programa apagados ni enciende).
  mantener_luces:
    name: Mantener luces (bypass)
    icon: mdi:hand-back-right
  # Flag interno: indica que hay un snapshot listo para restaurar.
  sala_snapshot_ready:
    name: Sala - Snapshot listo
    icon: mdi:camera-burst

input_number:
  # Minutos de apagado total por franja (el preaviso está incluido dentro del total)
  sala_off_manana:
    name: Sala - Apagado mañana (min)
    min: 1
    max: 180
    step: 1
    unit_of_measurement: min
  sala_off_mediodia:
    name: Sala - Apagado mediodía (min)
    min: 1
    max: 180
    step: 1
    unit_of_measurement: min
  sala_off_tarde:
    name: Sala - Apagado tarde (min)
    min: 1
    max: 180
    step: 1
    unit_of_measurement: min
  sala_off_noche:
    name: Sala - Apagado noche (min)
    min: 1
    max: 180
    step: 1
    unit_of_measurement: min
  sala_off_madrugada:
    name: Sala - Apagado madrugada (min)
    min: 1
    max: 180
    step: 1
    unit_of_measurement: min

  # Minutos de preaviso (independiente, pero incluido en el total)
  sala_preaviso:
    name: Sala - Preaviso (min)
    min: 1
    max: 30
    step: 1
    unit_of_measurement: min

  # Brillo ABSOLUTO si la estrategia es "brightness" (uno por franja)
  sala_brightness_manana:
    name: Sala - Brillo (mañana) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 70
  sala_brightness_mediodia:
    name: Sala - Brillo (mediodía) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 70
  sala_brightness_tarde:
    name: Sala - Brillo (tarde) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 60
  sala_brightness_noche:
    name: Sala - Brillo (noche) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 60
  sala_brightness_madrugada:
    name: Sala - Brillo (madrugada) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 15

  # % Fallback por franja (si estrategia=fallback y no hay snapshot disponible)
  sala_fallback_manana:
    name: Sala - Fallback (mañana) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 60
  sala_fallback_mediodia:
    name: Sala - Fallback (mediodía) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 60
  sala_fallback_tarde:
    name: Sala - Fallback (tarde) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 60
  sala_fallback_noche:
    name: Sala - Fallback (noche) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 60
  sala_fallback_madrugada:
    name: Sala - Fallback (madrugada) %
    min: 1
    max: 100
    step: 1
    unit_of_measurement: '%'
    initial: 15

# Escenas por franja (opcional). Si la estrategia es "scene", se usa el entity_id aquí definido.
input_text:
  sala_scene_manana:
    name: Sala - Escena (mañana)
    icon: mdi:white-balance-sunny
    max: 255
    initial: ""
  sala_scene_mediodia:
    name: Sala - Escena (mediodía)
    icon: mdi:weather-sunny
    max: 255
    initial: ""
  sala_scene_tarde:
    name: Sala - Escena (tarde)
    icon: mdi:weather-sunset
    max: 255
    initial: ""
  sala_scene_noche:
    name: Sala - Escena (noche)
    icon: mdi:weather-night
    max: 255
    initial: ""
  sala_scene_madrugada:
    name: Sala - Escena (madrugada)
    icon: mdi:weather-night
    max: 255
    initial: ""

# Estrategia por franja (elige UNA): scene / brightness / fallback
input_select:
  sala_strategy_manana:
    name: Sala - Estrategia (mañana)
    options: [scene, brightness, fallback]
    initial: fallback
  sala_strategy_mediodia:
    name: Sala - Estrategia (mediodía)
    options: [scene, brightness, fallback]
    initial: fallback
  sala_strategy_tarde:
    name: Sala - Estrategia (tarde)
    options: [scene, brightness, fallback]
    initial: fallback
  sala_strategy_noche:
    name: Sala - Estrategia (noche)
    options: [scene, brightness, fallback]
    initial: fallback
  sala_strategy_madrugada:
    name: Sala - Estrategia (madrugada)
    options: [scene, brightness, fallback]
    initial: fallback

# Temporizadores (visibles en UI)
timer:
  apagado_sala:
    name: Apagado total - Sala
    restore: true
  preaviso_sala:
    name: Preaviso - Sala
    restore: true

# ------------------------
# AUTOMATIZACIÓN 1: DETECTED
# ------------------------
automation:
  - id: sala_motion_detected_v9
    alias: Sala - motion - detected (v9)
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sala
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.mantener_luces
        state: "off"
    variables:
      # Normalizamos la parte del día (sensor.parte_del_dia)
      parte: >
        {{ states('sensor.parte_del_dia') | lower
           | replace('á','a') | replace('é','e') | replace('í','i')
           | replace('ó','o') | replace('ú','u') }}
      # Área y luces (ajustar area_id si tu área se llama diferente)
      area_id_sala: "sala_de_estar"
      luces_area: >
        {{ expand(area_entities(area_id_sala))
           | selectattr('entity_id','search','^light\\.')
           | map(attribute='entity_id') | list }}
      # Estrategia por franja (scene / brightness / fallback)
      strategy_map: >
        {{
          {
            'manana': states('input_select.sala_strategy_manana')|lower,
            'mediodia': states('input_select.sala_strategy_mediodia')|lower,
            'tarde': states('input_select.sala_strategy_tarde')|lower,
            'noche': states('input_select.sala_strategy_noche')|lower,
            'madrugada': states('input_select.sala_strategy_madrugada')|lower
          }
        }}
      strategy: "{{ strategy_map.get(parte, 'fallback') }}"
      # Brillos configurados (para 'brightness') por franja
      bright_map: >
        {{
          {
            'manana': states('input_number.sala_brightness_manana')|int,
            'mediodia': states('input_number.sala_brightness_mediodia')|int,
            'tarde': states('input_number.sala_brightness_tarde')|int,
            'noche': states('input_number.sala_brightness_noche')|int,
            'madrugada': states('input_number.sala_brightness_madrugada')|int
          }
        }}
      bright_pct: "{{ bright_map.get(parte, 60) }}"
      # Fallback % por franja (si no hay snapshot)
      fb_map: >
        {{
          {
            'manana': states('input_number.sala_fallback_manana')|int,
            'mediodia': states('input_number.sala_fallback_mediodia')|int,
            'tarde': states('input_number.sala_fallback_tarde')|int,
            'noche': states('input_number.sala_fallback_noche')|int,
            'madrugada': states('input_number.sala_fallback_madrugada')|int
          }
        }}
      fb_pct: "{{ fb_map.get(parte, 60) }}"
      # Escenas por franja
      scene_map: >
        {{
          {
            'manana': states('input_text.sala_scene_manana'),
            'mediodia': states('input_text.sala_scene_mediodia'),
            'tarde': states('input_text.sala_scene_tarde'),
            'noche': states('input_text.sala_scene_noche'),
            'madrugada': states('input_text.sala_scene_madrugada')
          }
        }}
      scene_entity_raw: "{{ scene_map.get(parte, '') }}"
      scene_entity: >
        {% set s = scene_entity_raw %}
        {{ s if s not in ['unknown','unavailable','',None] else '' }}
    action:
      # Siempre cancelamos timers al detectar movimiento
      - service: timer.cancel
        target:
          entity_id:
            - timer.apagado_sala
            - timer.preaviso_sala

      - choose:
          # ---- Estrategia: SCENE ----
          - conditions: "{{ strategy == 'scene' }}"
            sequence:
              - choose:
                  - conditions: "{{ scene_entity != '' }}"
                    sequence:
                      - service: scene.turn_on
                        data: { entity_id: "{{ scene_entity }}" }
                      - service: input_boolean.turn_off
                        target: { entity_id: input_boolean.sala_snapshot_ready }
                default:
                  # Si no hay escena definida, degradamos a FALLBACK
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: input_boolean.sala_snapshot_ready
                            state: "on"
                        sequence:
                          - service: scene.turn_on
                            data: { entity_id: scene.sala_snapshot }
                          - service: input_boolean.turn_off
                            target: { entity_id: input_boolean.sala_snapshot_ready }
                    default:
                      - service: light.turn_on
                        data:
                          entity_id: "{{ luces_area | join(', ') }}"
                          brightness_pct: "{{ fb_pct }}"

          # ---- Estrategia: BRIGHTNESS ----
          - conditions: "{{ strategy == 'brightness' }}"
            sequence:
              - service: light.turn_on
                data:
                  entity_id: "{{ luces_area | join(', ') }}"
                  brightness_pct: "{{ bright_pct }}"
              - service: input_boolean.turn_off
                target: { entity_id: input_boolean.sala_snapshot_ready }

          # ---- Estrategia: FALLBACK ----
          - conditions: []
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: input_boolean.sala_snapshot_ready
                        state: "on"
                    sequence:
                      - service: scene.turn_on
                        data: { entity_id: scene.sala_snapshot }
                      - service: input_boolean.turn_off
                        target: { entity_id: input_boolean.sala_snapshot_ready }
                default:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ luces_area | join(', ') }}"
                      brightness_pct: "{{ fb_pct }}"

# ------------------------
# AUTOMATIZACIÓN 2: CLEAR
# ------------------------
  - id: sala_motion_clear_v9
    alias: Sala - motion - clear (v9)
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sala
        to: "off"
        for: "00:00:05"   # debounce OFF 5s
    condition:
      - condition: state
        entity_id: input_boolean.mantener_luces
        state: "off"
    variables:
      parte: >
        {{ states('sensor.parte_del_dia') | lower
           | replace('á','a') | replace('é','e') | replace('í','i')
           | replace('ó','o') | replace('ú','u') }}
      # Minutos por franja (desde helpers)
      total_min: >-
        {% set mapa = {
          'manana': states('input_number.sala_off_manana')|int,
          'mediodia': states('input_number.sala_off_mediodia')|int,
          'tarde': states('input_number.sala_off_tarde')|int,
          'noche': states('input_number.sala_off_noche')|int,
          'madrugada': states('input_number.sala_off_madrugada')|int
        } %}
        {{ mapa.get(parte, states('input_number.sala_off_noche')|int) }}
      preaviso_min: "{{ states('input_number.sala_preaviso') | int }}"
      total_seg: "{{ (total_min | int) * 60 }}"
      preaviso_seg: "{{ (preaviso_min | int) * 60 }}"
      # Espera hasta el inicio del preaviso (total - preaviso), con piso 0
      espera_preaviso_s: "{{ [ (total_seg | int) - (preaviso_seg | int), 0 ] | max }}"
      # Duraciones para los timers
      dur_total: "00:{{ '%02d'|format(total_min | int) }}:00"
      dur_preaviso: "00:{{ '%02d'|format(preaviso_min | int) }}:00"
      # Área y luces
      area_id_sala: "sala_de_estar"
      luces_area: >
        {{ expand(area_entities(area_id_sala))
           | selectattr('entity_id','search','^light\\.')
           | map(attribute='entity_id') | list }}
    action:
      # 1) Iniciar timer TOTAL (visual en UI)
      - service: timer.start
        target: { entity_id: timer.apagado_sala }
        data: { duration: "{{ dur_total }}" }

      # 2) Esperar hasta el preaviso (o hasta que vuelva movimiento)
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.motion_sala
            to: "on"
        timeout:
          seconds: "{{ espera_preaviso_s | int }}"
        continue_on_timeout: true

      - choose:
          # Volvió movimiento antes del preaviso → cancelar y salir
          - conditions: "{{ wait.trigger is not none }}"
            sequence:
              - service: timer.cancel
                target:
                  entity_id:
                    - timer.apagado_sala
                    - timer.preaviso_sala
              - stop: "Movimiento volvió antes del preaviso."

        # 3) No volvió → crear snapshot (si hay luces ON) y marcar flag
        default:
          - choose:
              - conditions: >-
                  {{ expand(luces_area) | selectattr('state','eq','on') | list | length > 0 }}
                sequence:
                  - service: scene.create
                    data:
                      scene_id: sala_snapshot
                      snapshot_entities: "{{ luces_area }}"
                  - service: input_boolean.turn_on
                    target: { entity_id: input_boolean.sala_snapshot_ready }

          # 4) Dim relativo: bajar cada luz ON al 50% (piso 10%)
          - variables:
              encendidas: >
                {{ expand(luces_area)
                   | selectattr('state','eq','on')
                   | map(attribute='entity_id') | list }}
          - if:
              - condition: template
                value_template: "{{ encendidas | length > 0 }}"
            then:
              - repeat:
                  for_each: "{{ encendidas }}"
                  sequence:
                    - service: light.turn_on
                      data:
                        entity_id: "{{ repeat.item }}"
                        brightness_pct: >-
                          {% set b255 = state_attr(repeat.item,'brightness')|int(255) %}
                          {% set pct0 = (b255 / 2.55) | round(0) | int %}
                          {% set newp = (pct0 / 2) | int %}
                          {{ [newp, 10] | max }}

          # 5) Iniciar timer PREAVISO (independiente para UI)
          - service: timer.start
            target: { entity_id: timer.preaviso_sala }
            data: { duration: "{{ dur_preaviso }}" }

          # 6) Esperar: o vuelve movimiento, o termina preaviso
          - wait_for_trigger:
              - platform: state
                entity_id: binary_sensor.motion_sala
                to: "on"
              - platform: event
                event_type: timer.finished
                event_data: { entity_id: timer.preaviso_sala }
            timeout: "{{ dur_total }}"
            continue_on_timeout: true

          - choose:
              # 6.a) Volvió movimiento durante preaviso → restaurar snapshot (si hay) y cancelar timers
              - conditions: >-
                  {{ wait.trigger is not none and
                     (wait.trigger.platform == 'state' or
                      (wait.trigger.platform == 'event' and wait.trigger.event.data.entity_id == 'timer.preaviso_sala' and 0)) }}
                sequence:
                  - service: timer.cancel
                    target:
                      entity_id:
                        - timer.preaviso_sala
                        - timer.apagado_sala
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: input_boolean.sala_snapshot_ready
                            state: "on"
                        sequence:
                          - service: scene.turn_on
                            data: { entity_id: scene.sala_snapshot }
                  - service: input_boolean.turn_off
                    target: { entity_id: input_boolean.sala_snapshot_ready }
                  - stop: "Movimiento volvió durante el preaviso."

            # 6.b) No volvió → Apagado total y limpiar flag
            default:
              - service: light.turn_off
                data:
                  entity_id: "{{ luces_area | join(', ') }}"
              - service: input_boolean.turn_off
                target: { entity_id: input_boolean.sala_snapshot_ready }
