name: Lint and auto-fix YAML
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        id: lint
        run: |
          yamllint -f parsable . > lint-result.txt || true
          cat lint-result.txt
          if grep -q '^[^#[:space:]]' lint-result.txt; then
            echo "found_errors=true" >> "$GITHUB_OUTPUT"
          else
            echo "found_errors=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Node.js (for Prettier)
        if: steps.lint.outputs.found_errors == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Prettier
        if: steps.lint.outputs.found_errors == 'true'
        run: npm install --global prettier

      - name: Auto-format YAML files with Prettier
        if: steps.lint.outputs.found_errors == 'true'
        run: prettier --write "**/*.yaml"

      - name: Commit and push fixed files
        if: steps.lint.outputs.found_errors == 'true'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "fix: auto-format YAML after lint errors"
            git push
          else
            echo "No changes after formatting"
          fi
